{-|
Module      : Modsefa.Core.ValidatorScript
Description : Defines the interface for obtaining validator scripts in Modsefa.
Copyright   : (c) The Modsefa Project, 2025
License     : Apache-2.0
Maintainer  : nrmeyer@ptrx.xyz
Stability   : experimental
Portability : GHC

This module defines the 'AppValidatorScripts' type class, which serves as the
interface between the abstract Modsefa application specification ('AppSpec')
and the concrete implementations of its validator scripts ('GYScript').

Each specific Modsefa application (like `FeedApp` or `SubscriptionApp`) must provide
an instance of 'AppValidatorScripts'. This instance implements the 'getValidatorScript'
method, which is responsible for returning the appropriate parameterized validator script
('GYScript') based on the validator type ('Proxy v') and its resolved parameters
('ParamsToValue (Params v)'). This typically involves calling the compiled script
functions generated by Template Haskell (e.g., from `Modsefa.CodeGen.Generation`).
-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableSuperClasses #-}

module Modsefa.Core.ValidatorScript
 ( AppValidatorScripts(..)
 ) where

import Data.Kind (Type)
import Data.Proxy (Proxy)
import Data.Typeable (Typeable)

import GeniusYield.Types (GYScript)

import Modsefa.Core.Foundation
  ( AppSpec, ParamsToValue, ValidatorSpec(Params, ValidatorPlutusVersion)
  )


-- ============================================================================
-- Core HasValidatorScript Interface
-- ============================================================================

-- | Type class connecting a Modsefa 'AppSpec' (@app@) to its concrete validator script implementations.
-- An instance must be defined for each specific Modsefa application.
class AppSpec app => AppValidatorScripts (app :: Type) where
  -- | Retrieves the parameterized validator script ('GYScript') for a specific validator type (@v@)
  -- within the application @app@.
  --
  -- It takes a 'Proxy' to identify the validator type @v@ and the resolved, value-level
  -- parameters required by that validator's script. The 'ValidatorSpec v' and 'Typeable v'
  -- constraints allow the instance implementation to dispatch to the correct compiled script
  -- based on the type @v@.
  getValidatorScript :: forall v. (ValidatorSpec v, Typeable v) =>
    Proxy v -> -- ^ Proxy identifying the validator type (e.g., @Proxy \@MyValidator@).
    ParamsToValue (Params v) -> -- ^ The resolved value-level parameters for this validator instance.
    GYScript (ValidatorPlutusVersion v) -- ^ The resulting Genius Yield script, parameterized and ready for use.